services:
  conda-store-worker:
    image: quansight/conda-store-server:${CONDA_STORE_SERVER_VERSION:-2024.11.1}
    volumes:
      - ./docker/assets/environments:/opt/environments:ro
      - ./docker/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    depends_on:
      conda-store-server:
        condition: service_healthy
    platform: linux/amd64
    command:
      [
        "conda-store-worker",
        "--config",
        "/opt/conda_store/conda_store_config.py"
      ]

  conda-store-server:
    image: quansight/conda-store-server:${CONDA_STORE_SERVER_VERSION:-2024.11.1}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./docker/assets/conda_store_config.py:/opt/conda_store/conda_store_config.py:ro
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "http://localhost:8080/conda-store/api/v1/"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: linux/amd64
    command:
      [
        "conda-store-server",
        "--config",
        "/opt/conda_store/conda_store_config.py"
      ]
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: sh
    command: -c 'mkdir -p /data/conda-store && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

  postgres:
    image: postgres:13
    user: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conda-store

  redis:
    image: bitnami/redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      REDIS_PASSWORD: password

  conda-store-ui:
    build:
      context: .
      target: dev
    command: "yarn run start:ui"
    profiles:
      - local-dev
    ports:
      - "8000:8000"
    depends_on:
      conda-store-server:
        condition: service_healthy
    platform: linux/amd64
    volumes:
      - ./src:/usr/src/app/src
      - ./style:/usr/src/app/style
      - ./.env:/usr/src/app/.env
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "http://localhost:8000"]
      interval: 20s
      timeout: 10s
      retries: 8
