# Environment for developing the conda-store-ui and for running
# playwright tests

name: cs-ui-dev-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nodejs=18.18 # do not install Yarn separately, will get Yarn via Corepack
  - pytest
  - pip
  - pip:
      - playwright
      - pytest-playwright
