# Environment for developing the conda-store-ui and for running 
# playwright tests

name: test-env
channels:
- conda-forge
dependencies:
- python=3.10
- yarn
- nodejs==16.14.2
- pytest
- pip:
  - playwright
  - pytest-playwright