# Environment for developing the conda-store-ui and for running
# playwright tests

name: cs-ui-dev-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  # Match the version of Node.js defined in the Dockerfile.
  # Also, do not install Yarn separately, use Corepack (comes with Node.js).
  - nodejs >=22
  - pytest
  - pip
  - pip:
      - playwright
      - pytest-playwright
