# Environment for developing the conda-store-ui and for running
# playwright tests

name: cs-ui-dev-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - yarn>=4.4.0
  - nodejs>=18.0
  - pytest
  - pip
  - pip:
      - playwright
      - pytest-playwright
